<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /var/www/html/civisite/sites/default/files/civicrm/ext/com.sengii.manager/xml/schema/CRM/Manager/ActivityStream.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0ffcf86fe9e2de2a7cbc663dbf9a4a5e)
 */

/**
 * Database access object for the ActivityStream entity.
 */
class CRM_Manager_DAO_ActivityStream extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_activity_stream';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique ActivityStream ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Number of points associated with the action
   *
   * @var int unsigned
   */
  public $points;

  /**
   * Name of Person
   *
   * @var string
   */
  public $person_name;

  /**
   * CRM Identifier for Person (Source of action)
   *
   * @var string
   */
  public $person_crmid;

  /**
   * Person Identifier
   *
   * @var int unsigned
   */
  public $person_id;

  /**
   * Optional: Name of Group
   *
   * @var string
   */
  public $group_name;

  /**
   * Optional: CRM Identifier for Group (Target of action)
   *
   * @var string
   */
  public $group_crmid;

  /**
   * Optional: Group Identifier
   *
   * @var int unsigned
   */
  public $group_id;

  /**
   * Name of Target
   *
   * @var string
   */
  public $target_name;

  /**
   * Body of Target
   *
   * @var text
   */
  public $target_body;

  /**
   * CRM Identifier for Record (Exact Target of action)
   *
   * @var string
   */
  public $target_crmid;

  /**
   * Target Record Identifier
   *
   * @var int
   */
  public $target_id;

  /**
   * Target's Parent Record Identifier
   *
   * @var int
   */
  public $target_parent_id;

  /**
   * Links, Article, Event, Blog, Person, Event, Group, Asset, Group, Article, Forum, Comment, Message, Poll
   *
   * @var string
   */
  public $target_type;

  /**
   * DateTime of Action
   *
   * @var datetime
   */
  public $date;

  /**
   * Body of Action (description)
   *
   * @var text
   */
  public $action_body;

  /**
   * Request, Accept, Decline, Edit, Add, Remove, Invite, Watch, Picture, Login, Mobile, OptIn, RSVP
   *
   * @var string
   */
  public $verb;

  /**
   * Group, GroupMember, Profile, Contact, Question, Answer, Permission, Comment, Note, Rate, Favorite, Like, Wall, Person, Forum, Blog, Asset, Article, Event, Link, Message, Mobile, Privacy
   *
   * @var string
   */
  public $noun;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_activity_stream';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique ActivityStream ID',
          'required' => TRUE,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'points' => [
          'name' => 'points',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Points'),
          'description' => 'Number of points associated with the action',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'person_name' => [
          'name' => 'person_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Person Name'),
          'description' => 'Name of Person',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'person_crmid' => [
          'name' => 'person_crmid',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Person Crmid'),
          'description' => 'CRM Identifier for Person (Source of action)',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'person_id' => [
          'name' => 'person_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Person Identifier',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'group_name' => [
          'name' => 'group_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Group Name'),
          'description' => 'Optional: Name of Group',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'group_crmid' => [
          'name' => 'group_crmid',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Group Crmid'),
          'description' => 'Optional: CRM Identifier for Group (Target of action)',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'group_id' => [
          'name' => 'group_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Optional: Group Identifier',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'target_name' => [
          'name' => 'target_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Target Name'),
          'description' => 'Name of Target',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'target_body' => [
          'name' => 'target_body',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Target Body'),
          'description' => 'Body of Target',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'target_crmid' => [
          'name' => 'target_crmid',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Target Crmid'),
          'description' => 'CRM Identifier for Record (Exact Target of action)',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'target_id' => [
          'name' => 'target_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Target Record Identifier',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'target_parent_id' => [
          'name' => 'target_parent_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Target\'s Parent Record Identifier',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'target_type' => [
          'name' => 'target_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Target Type'),
          'description' => 'Links, Article, Event, Blog, Person, Event, Group, Asset, Group, Article, Forum, Comment, Message, Poll',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'date' => [
          'name' => 'date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Date'),
          'description' => 'DateTime of Action',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'action_body' => [
          'name' => 'action_body',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Action Body'),
          'description' => 'Body of Action (description)',
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'verb' => [
          'name' => 'verb',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Verb'),
          'description' => 'Request, Accept, Decline, Edit, Add, Remove, Invite, Watch, Picture, Login, Mobile, OptIn, RSVP',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
        'noun' => [
          'name' => 'noun',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Noun'),
          'description' => 'Group, GroupMember, Profile, Contact, Question, Answer, Permission, Comment, Note, Rate, Favorite, Like, Wall, Person, Forum, Blog, Asset, Article, Event, Link, Message, Mobile, Privacy',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_activity_stream',
          'entity' => 'ActivityStream',
          'bao' => 'CRM_Manager_DAO_ActivityStream',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'activity_stream', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'activity_stream', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
