-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2018                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2018                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_sengii_group`;
DROP TABLE IF EXISTS `civicrm_group_contact_cache`;
DROP TABLE IF EXISTS `civicrm_contact_group_cache`;
DROP TABLE IF EXISTS `civicrm_activity_stream`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_activity_stream
-- *
-- * Table for storing activity streams
-- *
-- *******************************************************/
CREATE TABLE `civicrm_activity_stream` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique ActivityStream ID',
     `points` int unsigned    COMMENT 'Number of points associated with the action',
     `person_name` varchar(0)    COMMENT 'Name of Person',
     `person_crmid` varchar(0)    COMMENT 'CRM Identifier for Person (Source of action)',
     `person_id` int unsigned    COMMENT 'Person Identifier',
     `group_name` varchar(0)    COMMENT 'Optional: Name of Group',
     `group_crmid` varchar(0)    COMMENT 'Optional: CRM Identifier for Group (Target of action)',
     `group_id` int unsigned    COMMENT 'Optional: Group Identifier',
     `target_name` varchar(0)    COMMENT 'Name of Target',
     `target_body` text    COMMENT 'Body of Target',
     `target_crmid` varchar(0)    COMMENT 'CRM Identifier for Record (Exact Target of action)',
     `target_id` int    COMMENT 'Target Record Identifier',
     `target_parent_id` int    COMMENT 'Target\'s Parent Record Identifier',
     `target_type` varchar(0)    COMMENT 'Links, Article, Event, Blog, Person, Event, Group, Asset, Group, Article, Forum, Comment, Message, Poll',
     `date` datetime    COMMENT 'DateTime of Action',
     `action_body` text    COMMENT 'Body of Action (description)',
     `verb` varchar(0)    COMMENT 'Request, Accept, Decline, Edit, Add, Remove, Invite, Watch, Picture, Login, Mobile, OptIn, RSVP',
     `noun` varchar(0)    COMMENT 'Group, GroupMember, Profile, Contact, Question, Answer, Permission, Comment, Note, Rate, Favorite, Like, Wall, Person, Forum, Blog, Asset, Article, Event, Link, Message, Mobile, Privacy' 
,
        PRIMARY KEY (`id`)
 
 
 
)    ;

-- /*******************************************************
-- *
-- * civicrm_group_contact_cache
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_group_contact_cache` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique GroupContactCache ID',
     `contact_id` int unsigned    COMMENT 'FK to Contact' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_group_contact_cache_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_sengii_group
-- *
-- * Used to track changes to the Group entities
-- *
-- *******************************************************/
CREATE TABLE `civicrm_sengii_group` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique SengiiGroup ID',
     `group_id` int unsigned    COMMENT 'FK to Group',
     `modified_date` datetime    COMMENT 'Date group was modified' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_sengii_group_group_id FOREIGN KEY (`group_id`) REFERENCES `civicrm_group`(`id`) ON DELETE CASCADE  
)    ;

 
